name: “Exemplo de CD”

on:
  push: # Nesse caso, vou considerar que o deploy sera feito quando um push for feito na branch main
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted # Aqui indicamos que sera executado em um agente proprio EC2
    steps:

    - name: Pull Docker image # Aqui estamos puxando a imagem do Docker Hub
      run: docker pull rafaellizarbe95/aula-ci:latest

    - name: Stop Docker container # Aqui estamos parando o container, caso ele esteja rodando
      run: docker stop ci-example || true

    - name: Remove Docker container # Aqui estamos removendo o container, caso ele exista
      run: docker rm ci-example || true

    - name: Run Docker container # Aqui estamos rodando o container
      run: docker run —-name ci-example -d -p 8080:8080 rafaellizarbe95/aula-ci:latest