name: Exemplo de CI # Nome da acdo

on:
  pull_request:
    branches:
      - main
      - develop
    types: [ opened, reopened]
  push: # Evento que ird disparar a a¢gao
    branches: [ main ] # Branch que ird disparar a a¢do

jobs: # Trabalhos a serem executados
  build:
    runs-on: ubuntu-latest # Sistema operacional a ser utilizado
    steps: # Passos a serem executados
    - name: Checkout code # Nome do passo, nesse caso, clonar o repositério
      uses: actions/checkout@v4 # action escolhida para clonar o repositério

    - name: Set up JDK 17 # Nome do passo, nesse caso, configurar 0 JDK 17
      uses: actions/setup-java@v4 # action escolhida para configurar o JDK
      with: # Configuragées da action
        distribution: 'temurin' # Distribui¢do do JDK
        java-version: '17' # Versdo do JDK

    - name: Build with Maven # Nome do passo, nesse caso, buildar com Maven
      run: mvn package -DskipTests # Comando a ser executado

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Test with Maven
      run: mvn test
