name: Exemplo de CI # Nome da acdo

on:
  pull_request:
    branches:
      - main
      - develop
    types: [ opened, reopened]
#  push: # Evento que irá disparar a ação
#    branches: [ main ] # Branch que irá disparar a ação

# Diga-me e eu esqueço, ensine-me e eu posso
#lembrar, envolva-me e eu aprendo. - Benjamin Franklin

jobs: # Trabalhos a serem executados
  build:
    runs-on: ubuntu-latest # Sistema operacional a ser utilizado
    steps: # Passos a serem executados
    - name: Checkout code # Nome do passo, nesse caso, clonar o repositério
      uses: actions/checkout@v4 # action escolhida para clonar o repositério

    - name: Set up JDK 17 # Nome do passo, nesse caso, configurar 0 JDK 17
      uses: actions/setup-java@v4 # action escolhida para configurar o JDK
      with: # Configuragées da action
        distribution: 'temurin' # Distribui¢do do JDK
        java-version: '17' # Versdo do JDK

    - name: Build with Maven # Nome do passo, nesse caso, buildar com Maven
      run: mvn package -DskipTests # Comando a ser executado

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Test with Maven
      run: mvn test

  docker:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker login DockerHub action
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: rafaellizarbe95/aula-ci:latest


